Numpy- Numpy is a fundamental library for scientific computing in python. it provides support for arrays and matrices,along with a collection of mathematical functions to operate on these data structures.

In [2]:
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1)
print(arr1.shape)
print(type(arr1))

[1 2 3 4]
(4,)
<class 'numpy.ndarray'>


In [11]:
arr2=np.array([1,2,3,4,5,6])
arr2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
np.arange(0,10,3).reshape(2,2)

array([[0, 3],
       [6, 9]])

In [22]:
np.ones((3,4))
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
arr1=np.array([[1,2,3,4,5,6],[0,1,2,3,4,5]])

print("Array",arr1)
print("shape",arr1.shape)
print("nor of dimensions",arr1.ndim)


Array [[1 2 3 4 5 6]
 [0 1 2 3 4 5]]
shape (2, 6)
nor of dimensions 2


In [31]:
# Number vectorised operation
arr1=np.array([1,2,3,4])
arr2=np.array([30,40,50,60])

# element wise addition
print("Addition:",arr1+arr2)

# element wise Substraction
print("Substraction:",arr2-arr1)

# element wise Multiplication
print("Multiplication:",arr1*arr2)

# element wise division
print("Division:",arr2/arr1)

Addition: [31 42 53 64]
Substraction: [29 38 47 56]
Multiplication: [ 30  80 150 240]
Division: [30.         20.         16.66666667 15.        ]


In [34]:
# universal Function
arr=np.array([2,3,4,5,6])

# square root
print("Square root:",np.sqrt(arr))

# exponential
print("Exponential:",np.exp(arr))

# sine
print("Sine:",np.sin(arr))

# natural log
print("natural log",np.log(arr))


Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
natural log [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


Array Slicing and Indexing

In [37]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1


In [41]:
print(arr [0][0])
print(arr[1:,2:])
print(arr[:2,:2])

1
[[ 7  8]
 [11 12]]
[[1 2]
 [5 6]]


Modifying the array

In [44]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[0][0]=100
print(arr)

arr[1:3,2:3]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6 100   8]
 [  9  10 100  12]]


Statastical concepts-Normalization
to have a mean of 0 and sd of 1


In [46]:
data=np.array([1,2,3,4,5])

# calculate mean and standard deviation

mean=np.mean(data)
std_dev=np.std(data)

# Normalize the data

Normalize=(data-mean)/std_dev
print("Normalize data:",Normalize)



Normalize data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [49]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean=np.mean(data)
print("Mean data:",mean)

# Median
Median=np.median(data)
print("Median data:",Median)

# std_dev
std_dev=np.std(data)
print("Standard deviation:",std_dev)

# variance
variance=np.var(data)
print("Variance:",variance)

Mean data: 5.5
Median data: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


logical opearation

In [51]:
data=np.array([1,2,3,4,5,6])
data>2
data[data>2]

array([3, 4, 5, 6])