In [2]:
%pip install numpy

In [14]:
import numpy as np
lst=[1,2,3,4,5]

print(type(lst))

arr=np.array(lst)

print(arr)

print(type(arr))

# ndarray means that it is ndimensional array

# to check wheather wich dementional array it wee use arr.ndim
twodarray=[[1,2,3],[4,5,6],[7,8,9]]
two=np.array(twodarray)
print(arr.ndim)
print(two.ndim)


# two.shape states what is the dimension of the like m&n values

print(two.shape)

# it is a 3*3 matrix

# arr.size-states how many elements are in the array

print(arr.size)

# np.zeros-initialises all the array elements into zeroes
zeros=np.zeros((3,5))
print(zeros)

# np.ones-initialises all the array elements into ones
ones=np.ones((3,5))
print(ones)

<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
1
2
(3, 3)
5
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
