In [2]:
import numpy as np

arr=np.random.random((3,3))
print(arr)

np.arange(1,10,2)
# here 1 is starting point 10 is ending point-1 and 2 is the difference

np.linspace(1,7,10)
# it would provide 10 elements in the range between 1,10

array=np.random.random((5,2))
print(array)

print("after")
array=np.reshape(array,(2,5))
print(array)

# reshape would change the dimensions of the array 


# arr.flaten it would convert n-dimensional arrays int one dimensional array

array.flatten()


[[0.19984453 0.32080313 0.23314503]
 [0.41058873 0.58082872 0.26791355]
 [0.07234604 0.56161221 0.12427053]]
[[0.76166988 0.60178559]
 [0.77513669 0.66199556]
 [0.12676958 0.10743241]
 [0.50624886 0.10167911]
 [0.58419076 0.14388523]]
after
[[0.76166988 0.60178559 0.77513669 0.66199556 0.12676958]
 [0.10743241 0.50624886 0.10167911 0.58419076 0.14388523]]


array([0.76166988, 0.60178559, 0.77513669, 0.66199556, 0.12676958,
       0.10743241, 0.50624886, 0.10167911, 0.58419076, 0.14388523])

various functions in the numpy


1.Arrange function:it creates an array by using the evenly spaced values over the given interval

syntax:numpy.arrange(start,stop,step,dtype)

where dtype:the data type of the numpy array items


In [4]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

2.size function: it counts the nor of elements in the array and along with axis
0-for rows, 1-for columns


In [7]:
arr=np.array([[1,2,3,5],[4,5,6,7],[7,8,9,10]])
print('total number of elements in array',arr.size)
print('rows',np.size(arr,0))
print('cols',np.size(arr,1))
print(arr)

total number of elements in array 12
rows 3
cols 4
[[ 1  2  3  5]
 [ 4  5  6  7]
 [ 7  8  9 10]]


3.shape function: used to find the dimensions that is no of rows and cols present

In [8]:
arr=np.array([[1,2,3,5],[4,5,6,7],[7,8,9,10]])
print(arr.shape)

(3, 4)


4) dtype Function :dtype in Python usually means the data type of the elements of a numpy array.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string

In [9]:
arr1 = np.array([1,2,3,1,2,3])
arr2 = np.array([1.2,3.1,2.3])
print(arr1.dtype)
print(arr2.dtype)


int32
float64


5) Ndim Function :The ndim attribute in NumPy provides the number of dimensions in an array ie 1-D , 2-D etc.

In [11]:
arr1 = np.array([1,2,3,1,2,3])
arr2 = np.array([[1,2,3],[1,2,3]])

print(arr1.ndim)
print(arr2.ndim)

arr3 = np.array(arr1, ndmin = 3)
print(arr3.ndim)
print(arr3)


1
2
3
[[[1 2 3 1 2 3]]]


6) Zeros Function : returns an array with the given shape and data type filled with zeros.

In [15]:
# Example 1: Create a 1D array of zeros
# With 7 elements and integer data type
arr = np.zeros(9)
print(arr)
# Example 2: Create a 1D array of zeros
# With 7 elements and integer data type
arr = np.zeros(7, int)
print(arr)
# Example 3: Create two-dimensional array with zeros
arr = np.zeros(shape=(4,5))
print(arr)
# Example 4: Create three-dimensional array with zeros
arr = np.zeros((4, 3, 5))
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


7) Ones function : used to create a new array of given shape and type, filled with ones.

Syntax : numpy.ones(shape, dtype = None)

In [16]:
arr = np.ones(shape = (3,5), dtype = int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


8) Eye Function : The eye tool returns a 2-D array with 1’s as the diagonal and 0’s elsewhere. The diagonal can be main, upper, or lower

Syntax : numpy.eye(n, m, dtype)


where : n :used for the nor of rows 

m :nor of the columns of the matrix

k:k is the diagonal value elem k>0.

dtype :This parameter is used to indicate the data type of the matrix. The default value of this parameter is float. This is an optional parameter.


np.eye(4, dtype = int)

In [21]:
np.eye(4, dtype = int)



array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

9) Empty Function: It is used to create a new array of given shapes and types, without initializing entries.

In [23]:
arr=np.empty()
arr

array([[9.18829272e-312, 7.60861095e-322, 0.00000000e+000,
        0.00000000e+000, 7.56571287e-307],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 6.98346901e-077],
       [1.81148490e-152, 9.37041222e-076, 1.05117820e-153,
        6.01391519e-154, 1.05121175e-153],
       [7.68132025e+140, 6.01347002e-154, 7.54951879e-096,
        1.95360725e-109, 4.90900643e+252],
       [1.94918511e-153, 6.32672800e+180, 4.74483502e+170,
        3.00948078e-067, 1.03724748e-314]])